# -*- coding: utf-8 -*-
"""Practice May 15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R48xJVrABZl2XHiCQZVDb5UqFiF5qvRf
"""

animals=['cat','dog',"horse"]
animals

for animal in animals:
  print(animal)

print(animals[0:0])
nums=list(range(5,12))
nums

for idx,animal in enumerate(animals):
  print('No {}-{}'.format(idx+1,animal))